AWSTemplateFormatVersion: '2010-09-09'
Description: "AWS Service Catalog Template - SSM Parameter Store with KMS Key"

Parameters:
  ParameterStoreName:
    Type: String
    Description: "Nombre del Parameter Store (formato kebab-case, ejemplo: my-app)"
    Default: "my-app"
    AllowedPattern: "^[a-z][a-z0-9-]*[a-z0-9]$"
    ConstraintDescription: "Debe usar formato kebab-case (letras minúsculas, números y guiones). Debe comenzar con letra y terminar con letra o número. Ejemplo: my-app"
  
  ParameterType:
    Type: String
    Description: "Tipo de parámetro"
    Default: "String"
    AllowedValues: 
      - "String"
      - "StringList"
      - "SecureString"
  
  ParameterValue:
    Type: String
    Description: "Valor inicial del parámetro"
    Default: "placeholder"
    NoEcho: true
  
  ParameterName:
    Type: String
    Description: "Nombre del parámetro (ejemplo: config)"
    Default: "config"
    AllowedPattern: "^[a-z][a-z0-9-]*[a-z0-9]$"
    ConstraintDescription: "Debe usar formato kebab-case (letras minúsculas, números y guiones). Debe comenzar con letra y terminar con letra o número."

Resources:
  # KMS Key para encriptar los parámetros
  KMSKey:
    Type: "AWS::KMS::Key"
    Properties:
      Description: "KMS Key para encriptar SSM Parameter Store"
      Enabled: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: "Enable IAM User Permissions"
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
          - Sid: "Allow access for Key Administrators"
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - "kms:Create*"
              - "kms:Describe*"
              - "kms:Enable*"
              - "kms:List*"
              - "kms:Put*"
              - "kms:Update*"
              - "kms:Revoke*"
              - "kms:Disable*"
              - "kms:Get*"
              - "kms:Delete*"
              - "kms:TagResource"
              - "kms:UntagResource"
              - "kms:ScheduleKeyDeletion"
              - "kms:CancelKeyDeletion"
            Resource: "*"
            Condition:
              StringEquals:
                'aws:PrincipalType': "User"
              StringLike:
                'aws:PrincipalArn': !Sub "arn:aws:iam::${AWS::AccountId}:user/admin/*"
          - Sid: "Allow SSM service to use the key"
            Effect: Allow
            Principal:
              Service: "ssm.amazonaws.com"
            Action:
              - "kms:Decrypt"
              - "kms:GenerateDataKey*"
            Resource: "*"
          - Sid: "Allow use of the key for SSM"
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - "kms:Encrypt"
              - "kms:Decrypt"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:DescribeKey"
            Resource: "*"
            Condition:
              StringEquals:
                "kms:ViaService": !Sub "ssm.${AWS::Region}.amazonaws.com"
  # Alias para la KMS Key
  KMSKeyAlias:
    Type: "AWS::KMS::Alias"
    Properties:
      AliasName: !Sub "alias/${ParameterStoreName}-kms"
      TargetKeyId: !Ref KMSKey
  SSMParameter:
    Type: "AWS::SSM::Parameter"
    DependsOn: 
      - KMSKey
      - KMSKeyAlias
    Properties:
      Name: !Sub "/${ParameterStoreName}/${ParameterName}"
      Type: !Ref ParameterType
      Value: !Ref ParameterValue
      Description: "Parámetro creado para almacenar información"
      Tier: "Standard"
      Tags: 
        Name: !Ref ParameterStoreName

Outputs:
  KMSKeyId:
    Description: "ID de la clave KMS creada"
    Value: !Ref KMSKey
  KMSKeyAlias:
    Description: "Alias de la clave KMS"
    Value: !Sub "${ParameterStoreName}-kms"
  ParameterName:
    Description: "Nombre del parámetro creado en SSM Parameter Store"
    Value: !Sub "/${ParameterStoreName}/${ParameterName}"
  ParameterStoreConsoleLink:
    Description: "Link directo al parámetro en la consola de AWS"
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/systems-manager/parameters/${ParameterStoreName}/${ParameterName}/description?region=${AWS::Region}"
